[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/xtensa-esp32s3-none-elf/debug/lilygo-t-display-s3-amoled-1_64"
firmware = "target/xtensa-esp32s3-none-elf/debug/lilygo-t-display-s3-amoled-1_64"
